version: '3.1'

services:
    rabbit1:
      image: "rabbitmq:3-management"
      hostname: "rabbit1"
      environment:
          RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "rabbitmq"
          RABBITMQ_DEFAULT_VHOST: "/"
      ports:
          - "15672:15672"

    nginx: 
        build: ./nginx
        links:
              - rabbit1
        ports:
              - 5000:5000
